<?php

namespace App\Filament\Resources;

use App\Filament\BaseResource;

use App\Filament\Concerns\HqOnly;
use App\Filament\Resources\StockTransferResource\Pages;
use App\Models\Branch;
use App\Models\CatalogProduct;
use App\Models\StockTransfer;
use App\Support\Translatable;
use Filament\Forms;
use Filament\Forms\Form;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;

/**
 * Stock-transfer ledger (read-only). Transfers are generated when a branch ORDER is
 * approved/fulfilled — the goods move from the seller (the branch the order was placed
 * with) to the buyer and the seller earns the stock-transfer commission. This screen
 * just shows that history; it is not a place to hand-enter single-item transfers.
 */
class StockTransferResource extends BaseResource
{
    use HqOnly;

    protected static ?string $model = StockTransfer::class;

    protected static ?string $navigationGroup = 'Trade';

    protected static ?string $navigationLabel = 'Stock Transfers';

    protected static ?string $navigationIcon = 'heroicon-o-truck';

    public static function canCreate(): bool
    {
        return false;   // generated by Order Request fulfilment, never hand-entered
    }

    // Audit ledger — belongs in the (future) Reports section, not the top-level sidebar.
    public static function shouldRegisterNavigation(): bool
    {
        return false;
    }

    public static function form(Form $form): Form
    {
        return $form->schema([
            Forms\Components\Section::make('Transfer')->columns(2)->schema([
                Forms\Components\Select::make('source_branch_id')
                    ->label('From (seller)')
                    ->options(fn () => self::branchOptions())
                    ->searchable()->required(),
                Forms\Components\Select::make('destination_branch_id')
                    ->label('To (buyer)')
                    ->options(fn () => self::branchOptions())
                    ->searchable()->required()
                    ->different('source_branch_id'),
                Forms\Components\Select::make('catalog_product_id')
                    ->label('Catalog item')
                    ->options(fn () => self::productOptions())
                    ->searchable()->required(),
                Forms\Components\DatePicker::make('transfer_date')->default(now()),
                Forms\Components\TextInput::make('weight')->label('Weight (g)')->numeric()->default(0)
                    ->helperText('For gold/silver.'),
                Forms\Components\TextInput::make('quantity')->label('Quantity (units)')->numeric()->default(0)
                    ->helperText('For vessels.'),
                Forms\Components\TextInput::make('unit_rate')->label('Unit rate (₹/g or ₹/unit)')->numeric()
                    ->helperText('Leave blank to use the live metal rate.'),
            ]),
        ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->defaultSort('transfer_date', 'desc')
            ->columns([
                Tables\Columns\TextColumn::make('transfer_no')->label('No')->searchable(),
                Tables\Columns\TextColumn::make('transfer_date')->date()->sortable(),
                Tables\Columns\TextColumn::make('sourceBranch.name')->label('From'),
                Tables\Columns\TextColumn::make('destinationBranch.name')->label('To'),
                Tables\Columns\TextColumn::make('seller_level')->badge()
                    ->formatStateUsing(fn (?string $s) => $s ? str($s)->replace('_', ' ')->title() : '—'),
                Tables\Columns\TextColumn::make('material')->badge(),
                Tables\Columns\TextColumn::make('transfer_value')->baseMoney()->label('Value'),
                Tables\Columns\TextColumn::make('margin_pct')->suffix('%')->label('Rate'),
                Tables\Columns\TextColumn::make('margin_amount')->baseMoney()->label('Margin'),
            ])
            ->actions([Tables\Actions\ViewAction::make()]);
    }

    protected static function branchOptions(): array
    {
        return Branch::query()->orderBy('name')->pluck('name', 'id')->all();
    }

    protected static function productOptions(): array
    {
        $default = Translatable::defaultLocale();

        return CatalogProduct::query()
            ->orderBy('code')
            ->get()
            ->mapWithKeys(fn (CatalogProduct $p) => [
                $p->id => trim($p->code . ' — ' . Translatable::pick($p->name, $default) . ' (' . $p->material . ')'),
            ])
            ->all();
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ListStockTransfers::route('/'),
            'view' => Pages\ViewStockTransfer::route('/{record}'),
        ];
    }
}
