<?php

namespace App\Filament\Resources\PayoutStatementResource\Pages;

use App\Filament\Resources\PayoutStatementResource;
use Filament\Resources\Pages\ListRecords;

class ListPayoutStatements extends ListRecords
{
    protected static string $resource = PayoutStatementResource::class;

    // Payout statements are generated by the engine (monthly roll-up), not hand-created.
    protected function getHeaderActions(): array
    {
        return [];
    }
}
