<?php

namespace App\Filament\Resources\PayrollRunResource\Pages;

use App\Filament\Resources\PayrollRunResource;
use App\Models\PayrollRun;
use App\Models\Payslip;
use Filament\Actions;
use Filament\Infolists\Components\Section;
use Filament\Infolists\Components\TextEntry;
use Filament\Infolists\Infolist;
use Filament\Resources\Pages\ViewRecord;

class ViewPayrollRun extends ViewRecord
{
    protected static string $resource = PayrollRunResource::class;

    /** Statutory registers the auditor asked for — PF and ESI contribution CSVs. */
    protected function getHeaderActions(): array
    {
        return [
            Actions\Action::make('pfRegister')
                ->label('PF register (CSV)')
                ->icon('heroicon-o-arrow-down-tray')
                ->action(fn () => $this->register('pf')),
            Actions\Action::make('esiRegister')
                ->label('ESI register (CSV)')
                ->icon('heroicon-o-arrow-down-tray')
                ->action(fn () => $this->register('esi')),
        ];
    }

    protected function register(string $kind)
    {
        /** @var PayrollRun $run */
        $run = $this->record;
        $slips = $run->payslips()->with('employee.member')->get()
            ->when($kind === 'pf', fn ($c) => $c->filter(fn (Payslip $s) => (float) $s->pf_employee > 0))
            ->when($kind === 'esi', fn ($c) => $c->filter(fn (Payslip $s) => (float) $s->esi_employee > 0));

        $headers = $kind === 'pf'
            ? ['UAN', 'Employee Code', 'Name', 'Gross Wages', 'PF Wages (Basic)', 'EPF Employee', 'EPF Employer']
            : ['ESIC No', 'Employee Code', 'Name', 'Payable Days', 'Gross Wages', 'ESI Employee', 'ESI Employer'];

        return response()->streamDownload(function () use ($kind, $slips, $headers) {
            $out = fopen('php://output', 'w');
            fputcsv($out, $headers);
            foreach ($slips as $s) {
                fputcsv($out, $kind === 'pf'
                    ? [$s->employee?->uan, $s->employee?->employee_code, $s->employee?->member?->name,
                        $s->gross, $s->basic, $s->pf_employee, $s->pf_employer]
                    : [$s->employee?->esic_number, $s->employee?->employee_code, $s->employee?->member?->name,
                        $s->payable_days, $s->gross, $s->esi_employee, $s->esi_employer]);
            }
            fclose($out);
        }, "{$kind}-register-{$run->periodLabel()}.csv", ['Content-Type' => 'text/csv']);
    }

    public function infolist(Infolist $infolist): Infolist
    {
        return $infolist->schema([
            Section::make('Run')->columns(4)->schema([
                TextEntry::make('period')->getStateUsing(fn (PayrollRun $r) => $r->periodLabel()),
                TextEntry::make('status')->badge()
                    ->color(fn ($state) => match ($state) {
                        'paid' => 'success', 'approved' => 'info', default => 'warning',
                    }),
                TextEntry::make('working_days'),
                TextEntry::make('generatedBy.name')->label('Generated by')->placeholder('—'),
                TextEntry::make('gross_total')->baseMoney(),
                TextEntry::make('deduction_total')->label('Deductions')->baseMoney(),
                TextEntry::make('net_total')->baseMoney(),
                TextEntry::make('paid_at')->dateTime()->placeholder('—'),
            ]),
        ]);
    }
}
